
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEQ = 27;
  public static final int DIVIDE = 13;
  public static final int STRING_LITERAL = 7;
  public static final int POWER = 14;
  public static final int CHAR = 31;
  public static final int CHAR_LITERAL = 3;
  public static final int POOL = 49;
  public static final int UMINUS = 16;
  public static final int RIGHT_SQUARE_BRACKET = 60;
  public static final int NOT_EQUAL = 58;
  public static final int LPAREN = 22;
  public static final int INT = 30;
  public static final int RAT_LITERAL = 6;
  public static final int MINUS = 11;
  public static final int RPAREN = 23;
  public static final int IMPLICATION = 42;
  public static final int AND = 40;
  public static final int NOT = 39;
  public static final int SEMICOLON = 21;
  public static final int IN = 53;
  public static final int OR = 41;
  public static final int TDEF = 34;
  public static final int BOOL = 36;
  public static final int COMMA = 17;
  public static final int LEFT_SHARP_EQUAL = 56;
  public static final int RAT = 32;
  public static final int LOOP = 48;
  public static final int PLUS = 10;
  public static final int IF = 45;
  public static final int MAIN = 2;
  public static final int DOT = 24;
  public static final int EOF = 0;
  public static final int RETURN = 52;
  public static final int EQUAL = 57;
  public static final int LEFT_SQUARE_BRACKET = 59;
  public static final int error = 1;
  public static final int NULL = 38;
  public static final int MOD = 15;
  public static final int LEFT_SHARP = 55;
  public static final int BREAK = 51;
  public static final int FDEF = 35;
  public static final int TOP = 28;
  public static final int TIMES = 12;
  public static final int COLON = 18;
  public static final int ENDIF = 47;
  public static final int ELSE = 50;
  public static final int DICT = 26;
  public static final int LBRACE = 19;
  public static final int READ = 43;
  public static final int FLOAT = 33;
  public static final int THEN = 46;
  public static final int RBRACE = 20;
  public static final int CONCATENATION = 54;
  public static final int LEN = 29;
  public static final int QUESTION = 25;
  public static final int ALIAS = 37;
  public static final int FLOAT_LITERAL = 4;
  public static final int PRINT = 44;
  public static final int BOOL_LITERAL = 8;
  public static final int INT_LITERAL = 5;
  public static final int IDENTIFIER = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "CHAR_LITERAL",
  "FLOAT_LITERAL",
  "INT_LITERAL",
  "RAT_LITERAL",
  "STRING_LITERAL",
  "BOOL_LITERAL",
  "IDENTIFIER",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "POWER",
  "MOD",
  "UMINUS",
  "COMMA",
  "COLON",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "LPAREN",
  "RPAREN",
  "DOT",
  "QUESTION",
  "DICT",
  "SEQ",
  "TOP",
  "LEN",
  "INT",
  "CHAR",
  "RAT",
  "FLOAT",
  "TDEF",
  "FDEF",
  "BOOL",
  "ALIAS",
  "NULL",
  "NOT",
  "AND",
  "OR",
  "IMPLICATION",
  "READ",
  "PRINT",
  "IF",
  "THEN",
  "ENDIF",
  "LOOP",
  "POOL",
  "ELSE",
  "BREAK",
  "RETURN",
  "IN",
  "CONCATENATION",
  "LEFT_SHARP",
  "LEFT_SHARP_EQUAL",
  "EQUAL",
  "NOT_EQUAL",
  "LEFT_SQUARE_BRACKET",
  "RIGHT_SQUARE_BRACKET"
  };
}

