
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORALL = 38;
  public static final int SEQ = 9;
  public static final int POW = 26;
  public static final int STRING_LITERAL = 14;
  public static final int MULT = 24;
  public static final int CHAR = 3;
  public static final int CHAR_LITERAL = 12;
  public static final int CONCAT = 28;
  public static final int R_SQUARE = 51;
  public static final int L_ROUND = 48;
  public static final int INT = 7;
  public static final int R_ROUND = 49;
  public static final int RAT_LITERAL = 16;
  public static final int ENDDO = 45;
  public static final int MINUS = 23;
  public static final int SEMICOLON = 58;
  public static final int NOT = 20;
  public static final int AND = 18;
  public static final int IN = 27;
  public static final int OR = 19;
  public static final int TDEF = 29;
  public static final int COMMA = 56;
  public static final int BOOL = 2;
  public static final int DIV = 25;
  public static final int RAT = 8;
  public static final int PLUS = 22;
  public static final int LESSEQ = 59;
  public static final int IF = 39;
  public static final int MAIN = 33;
  public static final int DOT = 57;
  public static final int EOF = 0;
  public static final int RETURN = 34;
  public static final int L_CURLY = 52;
  public static final int error = 1;
  public static final int R_CURLY = 53;
  public static final int EQEQ = 60;
  public static final int FDEF = 30;
  public static final int VOID = 32;
  public static final int EQ = 55;
  public static final int IMPLY = 21;
  public static final int TOP = 10;
  public static final int COLON = 54;
  public static final int L_ANGLE = 46;
  public static final int ENDIF = 43;
  public static final int ELSE = 41;
  public static final int DICT = 4;
  public static final int R_ANGLE = 47;
  public static final int L_SQUARE = 50;
  public static final int READ = 35;
  public static final int WHILE = 37;
  public static final int FLOAT = 5;
  public static final int THEN = 40;
  public static final int STRING = 11;
  public static final int ALIAS = 31;
  public static final int FLOAT_LITERAL = 17;
  public static final int ELIF = 42;
  public static final int DO = 44;
  public static final int PRINT = 36;
  public static final int BOOL_LITERAL = 13;
  public static final int NOTEQ = 61;
  public static final int INT_LITERAL = 15;
  public static final int IDENTIFIER = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "CHAR",
  "DICT",
  "FLOAT",
  "IDENTIFIER",
  "INT",
  "RAT",
  "SEQ",
  "TOP",
  "STRING",
  "CHAR_LITERAL",
  "BOOL_LITERAL",
  "STRING_LITERAL",
  "INT_LITERAL",
  "RAT_LITERAL",
  "FLOAT_LITERAL",
  "AND",
  "OR",
  "NOT",
  "IMPLY",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "POW",
  "IN",
  "CONCAT",
  "TDEF",
  "FDEF",
  "ALIAS",
  "VOID",
  "MAIN",
  "RETURN",
  "READ",
  "PRINT",
  "WHILE",
  "FORALL",
  "IF",
  "THEN",
  "ELSE",
  "ELIF",
  "ENDIF",
  "DO",
  "ENDDO",
  "L_ANGLE",
  "R_ANGLE",
  "L_ROUND",
  "R_ROUND",
  "L_SQUARE",
  "R_SQUARE",
  "L_CURLY",
  "R_CURLY",
  "COLON",
  "EQ",
  "COMMA",
  "DOT",
  "SEMICOLON",
  "LESSEQ",
  "EQEQ",
  "NOTEQ"
  };
}

